
// REGISTER
export const CATEGORIE_REGISTER_REQUEST = "CATEGORIE_REGISTER_REQUEST";
export const CATEGORIE_REGISTER_SUCESS = "CATEGORIE_REGISTER_SUCESS";
export const CATEGORIE_REGISTER_FAIL = "CATEGORIE_REGISTER_FAIL";
// DETAILS
export const CATEGORIE_DETAILS_REQUEST = "CATEGORIE_DETAILS_REQUEST";
export const CATEGORIE_DETAILS_SUCESS = "CATEGORIE_DETAILS_SUCESS";
export const CATEGORIE_DETAILS_FAIL = "CATEGORIE_DETAILS_FAIL";
export const CATEGORIE_DETAILS_RESET = "CATEGORIE_DETAILS_RESET";
// LIST
export const CATEGORIE_LIST_REQUEST = "CATEGORIE_LIST_REQUEST";
export const CATEGORIE_LIST_SUCESS = "CATEGORIE_LIST_SUCESS";
export const CATEGORIE_LIST_FAIL = "CATEGORIE_LIST_FAIL";
export const CATEGORIE_LIST_RESET = "CATEGORIE_LIST_RESET";
// DELETE
export const CATEGORIE_DELETE_REQUEST = "CATEGORIE_DELETE_REQUEST";
export const CATEGORIE_DELETE_SUCESS = "CATEGORIE_DELETE_SUCESS";
export const CATEGORIE_DELETE_FAIL = "CATEGORIE_DELETE_FAIL";
export const CATEGORIE_DELETE_RESET = "CATEGORIE_DELETE_RESET";
// UPDATE
export const CATEGORIE_UPDATE_REQUEST = "CATEGORIE_UPDATE_REQUEST";
export const CATEGORIE_UPDATE_SUCESS = "CATEGORIE_UPDATE_SUCESS";
export const CATEGORIE_UPDATE_FAIL = "CATEGORIE_UPDATE_FAIL";
export const CATEGORIE_UPDATE_RESET = "CATEGORIE_UPDATE_RESET";
