
// CREATE
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCESS = "ORDER_CREATE_SUCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";
// // DETAILS
// export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
// export const PRODUCT_DETAILS_SUCESS = "PRODUCT_DETAILS_SUCESS";
// export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
// export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";
// // LIST
// export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
// export const PRODUCT_LIST_SUCESS = "PRODUCT_LIST_SUCESS";
// export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
// export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";
// // DELETE
// export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
// export const PRODUCT_DELETE_SUCESS = "PRODUCT_DELETE_SUCESS";
// export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
// export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";
// // UPDATE
// export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
// export const PRODUCT_UPDATE_SUCESS = "PRODUCT_UPDATE_SUCESS";
// export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
// export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";
