
// CREATE
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCESS = "ORDER_CREATE_SUCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";
// DETAILS
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCESS = "ORDER_DETAILS_SUCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";
// // LIST
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCESS = "ORDER_LIST_SUCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";
// // UPDATE
export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCESS = "ORDER_UPDATE_SUCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";
// // DELETE
// export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
// export const PRODUCT_DELETE_SUCESS = "PRODUCT_DELETE_SUCESS";
// export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
// export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";
// // UPDATE
// export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
// export const PRODUCT_UPDATE_SUCESS = "PRODUCT_UPDATE_SUCESS";
// export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
// export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";
